// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Todo struct {
	ID          uuid.UUID
	Title       string
	Description string
	Done        sql.NullBool
	UserID      uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Name     string
	Age      int32
	Password string
}
